<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="phantomx" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926"/>
  <xacro:property name="width" value="0.08" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height1" value="0.086" /> <!-- Link 1 -->
  <xacro:property name="height2" value="0.042" /> <!-- Link 2 -->
  <xacro:property name="height3" value="0.106" /> <!-- Link 3 -->
  <xacro:property name="height4" value="0.106" /> <!-- Link 4 -->
  <xacro:property name="height5" value="0.07" /> <!-- Link 5 -->
  <xacro:property name="height6" value="0.02" /> <!-- Link 6 -->
  <xacro:property name="camera_link" value="0.05" /> <!-- Size of square 'camera' box -->
  <xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->
  <xacro:property name="ratio" value="0.01" /> <!-- for zooming the meshes -->

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find phantomx_description)/urdf/phantomx.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find phantomx_description)/urdf/materials.xacro" />

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="link1"/>
  </joint>

  <!-- Base Link -->
  <link name="link1">
    <collision>
      <origin xyz="-0.1 -0.135 0.0" rpy="${-0.0*PI} 0  ${-0.0*PI}"/>
      <geometry>
		<mesh filename="package://phantomx_description/meshes/Base.stl" scale="${ratio} ${ratio} ${ratio}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="-0.1 -0.135 0.0" rpy="${-0.0*PI} 0  ${-0.0*PI}"/>
      <geometry>
		<mesh filename="package://phantomx_description/meshes/Base.stl" scale="${ratio} ${ratio} ${ratio}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
	  ixx="0.1" ixy="0.0" ixz="0.0"
	  iyy="0.1" iyz="0.0"
	  izz="0.1"/>
    </inertial>
  </link>

  <joint name="arm_shoulder_pan_joint" type="revolute">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 0. ${height1}" rpy="0 0 0"/>
    <limit lower="${-1.0*PI}" upper="${1.0*PI}" effort="10.0" velocity="2"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7" />
  </joint>

  <link name="link2">
    <collision>
      <origin xyz="-0.0 -0.0 0.0" rpy="${0.5*PI} 0  ${0.0*PI}"/>
      <geometry>
		<mesh filename="package://phantomx_description/meshes/Shoulder.stl" scale="${ratio} ${ratio} ${ratio}"/>
      </geometry>
      <material name="black"/>
    </collision>

    <visual>
      <origin xyz="-0.0 -0.0 0.0" rpy="${0.5*PI} 0  ${0.0*PI}"/>
      <geometry>
		<mesh filename="package://phantomx_description/meshes/Shoulder.stl" scale="${ratio} ${ratio} ${ratio}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
	  ixx="0.1" ixy="0.0" ixz="0.0"
	  iyy="0.1" iyz="0.0"
	  izz="0.1"/>
    </inertial>
  </link>

  <joint name="arm_shoulder_lift_joint" type="revolute">
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="0 0. ${height2}" rpy="0 0 0"/>
    <limit lower="${-0.75*PI}" upper="${0.75*PI}" effort="10.0" velocity="2"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7" />
  </joint>


  <link name="link3">
    <collision>
      <origin xyz="-0.0 -0.0 0.0" rpy="${0.5*PI} 0  ${0.0*PI}"/>
      <geometry>
		<mesh filename="package://phantomx_description/meshes/Bicep.stl" scale="${ratio} ${ratio} ${ratio}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="-0.0 -0.0 0.0" rpy="${0.5*PI} 0  ${0.0*PI}"/>
      <geometry>
		<mesh filename="package://phantomx_description/meshes/Bicep.stl" scale="${ratio} ${ratio} ${ratio}"/>
      </geometry>
        <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
	  ixx="0.1" ixy="0.0" ixz="0.0"
	  iyy="0.1" iyz="0.0"
	  izz="0.1"/>
    </inertial>
  </link>


  <joint name="arm_elbow_flex_joint" type="revolute">
    <parent link="link3"/>
    <child link="link4"/>
    <origin xyz="0 0. ${height3}" rpy="0 0 0"/>
    <limit lower="${-0.8*PI}" upper="${0.8*PI}" effort="10.0" velocity="2"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7" />
  </joint>

  <link name="link4">
    <collision>
      <origin xyz="-0.0 -0.0 0.0" rpy="${0.5*PI} 0  ${0.0*PI}"/>
      <geometry>
		<mesh filename="package://phantomx_description/meshes/Bicep.stl" scale="${ratio} ${ratio} ${ratio}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="-0.0 -0.0 0.0" rpy="${0.5*PI} 0  ${0.0*PI}"/>
      <geometry>
		<mesh filename="package://phantomx_description/meshes/Bicep.stl" scale="${ratio} ${ratio} ${ratio}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
	  ixx="0.1" ixy="0.0" ixz="0.0"
	  iyy="0.1" iyz="0.0"
	  izz="0.1"/>
    </inertial>
  </link>


<joint name="arm_wrist_flex_joint" type="revolute">
    <parent link="link4"/>
    <child link="link5"/>
    <origin xyz="0 0. ${height4}" rpy="0 0 0"/>
    <limit lower="${-0.55*PI}" upper="${0.55*PI}" effort="10.0" velocity="2"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7" />
  </joint>

  <link name="link5">
    <collision>
      <origin xyz="0.012 -0.0 ${0.5*height5}" rpy="${-0.5*PI} 0  ${1.0*PI}"/>
      <geometry>
		<mesh filename="package://phantomx_description/meshes/Wrist.stl" scale="${ratio} ${ratio} ${ratio}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0.012 -0.0 ${0.5*height5}" rpy="${-0.5*PI} 0  ${1.0*PI}"/>
      <geometry>
		<mesh filename="package://phantomx_description/meshes/Wrist.stl" scale="${ratio} ${ratio} ${ratio}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
	  ixx="0.1" ixy="0.0" ixz="0.0"
	  iyy="0.1" iyz="0.0"
	  izz="0.1"/>
    </inertial>
  </link>

<joint name="camera_joint" type="fixed">
    <parent link="link5"/>
    <child link="kinect_link"/>
    <origin xyz="0.05 0. ${height5+0.005}" rpy="0 0 0"/>
  </joint>


    <link name="kinect_link">
      <inertial>
        <mass value="0.01" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.001"  ixy="0.0"  ixz="0.0"
                 iyy="0.001"  iyz="0.0"
                 izz="0.001" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="0.001 0.001 0.001" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="0.001 0.001 0.001" />
        </geometry>
      </collision>
    </link>



<joint name="joint5" type="fixed">
    <parent link="link5"/>
    <child link="link6"/>
    <origin xyz="0 0. ${height5+0.005}" rpy="0 0 0"/>
    <!--axis xyz="0 0 1"/>
    <dynamics damping="0.7" /-->
  </joint>

  <link name="link6">
    <collision>
      <origin xyz="-0.013 -0.011 ${-0.05*height5}" rpy="${-0.0*PI} 0  ${0.5*PI}"/>
      <geometry>
		<mesh filename="package://phantomx_description/meshes/Guide_Rail_Fixed.stl" scale="${ratio} ${ratio} ${ratio}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="-0.013 -0.011 ${-0.05*height5}" rpy="${-0.0*PI} 0  ${0.5*PI}"/>
      <geometry>
		<mesh filename="package://phantomx_description/meshes/Guide_Rail_Fixed.stl" scale="${ratio} ${ratio} ${ratio}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0.0 0.0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
	  ixx="0.1" ixy="0.0" ixz="0.0"
	  iyy="0.1" iyz="0.0"
	  izz="0.1"/>
    </inertial>
  </link>


 <joint name="gripper_joint" type="prismatic">
        <axis xyz="0 1 0" />
        <origin xyz="0 0.025 0.001" rpy="0 0 0"/>
        <limit effort="10.0" lower="-0.025" upper="0.025" velocity="0.2"/>
        <dynamics damping="1000.0"/>
        <parent link="link6"/>
        <child link="finger1_link"/>
  </joint>

  <link name="finger1_link">
    <collision>
      <origin xyz="0 -0.02 0.0105" rpy="0 0 ${-0.5*PI}"/>
      <geometry>
		<mesh filename="package://phantomx_description/meshes/finger.stl" scale="${ratio} ${ratio} ${ratio}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 -0.02 0.0105" rpy="0 0 ${-0.5*PI}"/>
      <geometry>
		<mesh filename="package://phantomx_description/meshes/finger.stl" scale="${ratio} ${ratio} ${ratio}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <mass value="8e-2" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-3" ixy="0" ixz="0" iyy="1e-3" iyz="0" izz="1e-3" />
    </inertial>
  </link>

<joint name="gripper_passive_joint" type="fixed">
    <axis xyz="0 -1 0" />
    <origin xyz="0 -0.025 0.001" rpy="0 0 0"/>
    <limit effort="10.0" lower="-0.025" upper="0.025" velocity="0.2"/>
      <dynamics damping="1000.0"/>
    <parent link="link6"/>
    <child link="finger2_link"/>
    <!--mimic label is not supported by gazebo for the moment --> 
    <mimic joint="gripper_joint" multiplier="-1" offset="0"/> 
  </joint>

   <link name="finger2_link">
    <collision>
      <origin xyz="0 0.02 0.0105" rpy="0 0 ${0.5*PI}"/>
      <geometry>
		<mesh filename="package://phantomx_description/meshes/finger.stl" scale="${ratio} ${ratio} ${ratio}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0.02 0.0105" rpy="0 0 ${0.5*PI}"/>
      <geometry>
		<mesh filename="package://phantomx_description/meshes/finger.stl" scale="${ratio} ${ratio} ${ratio}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <mass value="8e-2" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-3" ixy="0" ixz="0" iyy="1e-3" iyz="0" izz="1e-3" />
    </inertial>
  </link>

  <transmission name="joint1_trans" type="pr2_mechanism_model/SimpleTransmission">
    <type>transmission_interface/SimpleTransmission</type>
    <actuator name="motor1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
    <joint name="arm_shoulder_pan_joint"/>
  </transmission>

  <transmission name="joint2_trans" type="pr2_mechanism_model/SimpleTransmission">
    <type>transmission_interface/SimpleTransmission</type>
    <actuator name="motor2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
    <joint name="arm_shoulder_lift_joint"/>
  </transmission>

<transmission name="joint3_trans" type="pr2_mechanism_model/SimpleTransmission">
    <type>transmission_interface/SimpleTransmission</type>
    <actuator name="motor3">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
    <joint name="arm_elbow_flex_joint"/>
  </transmission>

  <transmission name="joint4_trans" type="pr2_mechanism_model/SimpleTransmission">
    <type>transmission_interface/SimpleTransmission</type>
    <actuator name="motor4">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
    <joint name="arm_wrist_flex_joint"/>
  </transmission>

 <transmission name="joint_gripper_trans" type="pr2_mechanism_model/SimpleTransmission">
    <type>transmission_interface/SimpleTransmission</type>
    <actuator name="motor8">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
    <joint name="gripper_joint"/>
    <mechanicalReduction>1.0</mechanicalReduction>
  </transmission>

 <transmission name="joint_finger2_trans" type="pr2_mechanism_model/SimpleTransmission">
    <type>transmission_interface/SimpleTransmission</type>
    <actuator name="motor9">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
    <joint name="gripper_passive_joint"/>
    <mechanicalReduction>1.0</mechanicalReduction>
  </transmission>

</robot>
