phantomx:
  # Publish all joint states -----------------------------------
  /joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  /joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_shoulder_pan_joint
    pid: {p: 100.0, i: 0.01, d: 0.0}
  /joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_shoulder_lift_joint
    pid: {p: 100.0, i: 0.01, d: 0.0}
  /joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_elbow_flex_joint
    pid: {p: 100.0, i: 0.01, d: 0.0}
  /joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_wrist_flex_joint
    pid: {p: 100.0, i: 0.01, d: 0.0}
  /joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: gripper_joint
    pid: {p: 100.0, i: 0.01, d: 0.0}
  /joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: gripper_passive_joint
    pid: {p: 100.0, i: 0.01, d: 0.0}

  /trajectory_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - arm_shoulder_pan_joint
      - arm_shoulder_lift_joint
      - arm_elbow_flex_joint
      - arm_wrist_flex_joint

    gains: # Required because we're controlling an effort interface
      arm_shoulder_pan_joint: {p: 100,  d: 0, i: 1, i_clamp: 1}
      arm_shoulder_lift_joint: {p: 100,  d: 0, i: 1, i_clamp: 1}
      arm_elbow_flex_joint: {p: 100,  d: 0, i: 1, i_clamp: 1}
      arm_wrist_flex_joint: {p: 100,  d: 0, i: 1, i_clamp: 1}
 
  /gripper_controller:
    # type: "effort_controllers/JointTrajectoryController"
    type: "position_controllers/GripperActionController"
    joint: gripper_joint
    goal_tolerance: 0.01
    stalled_velocity_threshold: 0.01
    stall_timeout: 0.2
    /gazebo_ros_control/pid_gains:
      gripper_joint: {p: 200, d: 0, i: 5}


